In [1]:
import numpy as np

In [17]:
my_array=np.array([[1,2,3,4,5]])
my_array

array([[1, 2, 3, 4, 5]])

In [18]:
my_array[0,1]

np.int64(2)

In [19]:
my_array


array([[1, 2, 3, 4, 5]])

In [20]:
my_array[0,1]

np.int64(2)

In [25]:
my_array.shape

(1, 5)

In [26]:
my_array

array([[1, 2, 3, 4, 5]])

In [29]:
my_array[0,2]=23

In [30]:
my_array

array([[ 1,  2, 23,  4,  5]])

In [31]:
my_array=np.int32()

In [33]:
my_array.dtype

dtype('int32')

In [ ]:
#Array Creation Conversion From Python Struc